### ISSUE TITLE
Map display in gui jumps to random display location

### ISSUE THREAD

**Issue by JCHJones** [BCLab-UNM/SwarmBaseCode-ROS#139]
When the rover is in auto mode, the map is displaying odom and map data in the gui and panning and zoom is set to manual. 

Sometimes if the user attempts to pan the map will jump to some off screen location when the user left clicks. This does not appear to happen when the rover is in auto mode.

Currently only re-produced when using physical rovers untested when using simulated rovers.

**Comment by JCHJones** [comment]
@Antonio-Griego requesting update

**Comment by Antonio-Griego** [comment]
This issue is addressed in pull request #202
