### ISSUE TITLE
Issue in ObstacleController.cpp for counting tags

### ISSUE THREAD

**Issue by jschlind411** [BCLab-UNM/SwarmBaseCode-ROS#154]
Issue inside setTagData where a double for loop creates a tag^n problem.  Does not impact current code but will impact anybody attempting to count total tags seen inside this controller.

**Comment by wfvining** [comment]
Erroneously counts cubes as well as collection zone tags.

**Comment by JCHJones** [comment]
@wfvining Requesting update
