### ISSUE TITLE
Issue with Gazebo Sim and objects not updating

### ISSUE THREAD

**Issue by jschlind411** [BCLab-UNM/SwarmBaseCode-ROS#155]
When running the simulation and moving the center or adding objects into the simulation, sometimes the objects do not show or change position.  It might be trying to update the object in an inefficient manner.

Also when in simulation, if the gazebo client crashes, when attempting to reload the gazebo window it will not update any information inside the gazebo window (time running, sim time, real time, etc.) as well as objects will not update at all in this state.  This results in having to restart the simulation to gain access back to the environment.

**Comment by wfvining** [comment]
Appears to be a gazebo bug.
