### ISSUE TITLE
can't run run.sh

### ISSUE THREAD

**Issue by amatii** [BCLab-UNM/SwarmBaseCode-ROS#184]
I get "qt_gui_main() found no plugin matching "rqt_rover_gui"" error when running run.sh. I followed your instructions, and I want to simulate it using Gazebo. it probably because of my set up, not your code.

**Comment by wfvining** [comment]
Could you provide a bit more information? It is possible that the GUI wasn't compiled successfully, or that the environment is not set up correctly.

**Comment by gmfricke** [comment]
No response from @amatii. Cannot replicate in house. Closing.
