### ISSUE TITLE
Can't parse gazebo message

### ISSUE THREAD

**Issue by gmfricke** [BCLab-UNM/SwarmBaseCode-ROS#191]
Rover GUI Starting...
[ INFO] [1533222582.062303311]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1533222582.062957752]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Setting up world... done.
[ INFO] [1533222583.523767230, 0.076000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1533222583.574261722, 1.770000000]: Physics dynamic reconfigure ready.
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "gazebo.msgs.Subscribe" because it is missing required fields: host, port, msg_type
Master Unknown message type[] From[58622]
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "gazebo.msgs.Packet" because it is missing required fields: stamp, type, serialized_data
Master Unknown message type[] From[58622]

**Comment by JCHJones** [comment]
Is this gazebo's fault
