### ISSUE TITLE
Gripper sim movement slow

### ISSUE THREAD

**Issue by gmfricke** [BCLab-UNM/SwarmBaseCode-ROS#204]
The gripper needs to move at the same rate in sim as in the physical robots.

**Comment by JCHJones** [comment]
This parameter can be changed without any negative impacts on real time sims. 

It however will reduce the maximum safe sim speed significantly as the gripper tends to fall apart when sim speed increased. I would recommend recapping the sim speed to real time if we reduce this parameter.

I would like a verification of this kind of behavior from someone besides me.

**Comment by gmfricke** [comment]
@Antonio-Griego will test this again. We can cap the simulation time to make it more realistic. @JCHJones what is the parameter to set to cap the sim speed?

**Comment by darrenchurchill** [comment]
What sim speeds are you getting on your computers? As the rqt gui calculates it, I get ~2.5x with one rover, and I don't think I've seen the gripper model have any issues when running the base code with this modification to the finger and wrist joints. What exactly do you mean when you say the gripper falls apart? Are there any error messages that would come through in the logs?

**Comment by Antonio-Griego** [comment]
fixed by #215
