### ISSUE TITLE
Rosbridge corrections

### ISSUE THREAD

**Issue by Carter90** [BCLab-UNM/SwarmBaseCode-ROS#210]
executable bit missing on rover_launch_local.sh need `chmod +x ./misc/rover_launch_local.sh`
and incorrect relative path in rover_launch_local to rover_onboard_node_launch should be `./misc/rover_onboard_node_launch`

There were missing instructions on the readme possibly 
npm is not installed on Ubuntu defaultly need to run `sudo apt install npm`?

in swarmie-web.js
`ros : robotRos` change to `ros : swarmieName.robotRos,`
on lines 20, 26, 32, 38, 171, 240, 265, 290, 316
remove .toUpperCase() as most hostnames are lowercase 
on line 12

`dicument` should be `document` on line 377

**Comment by wfvining** [comment]
the node.js stuff is cruft. I included it in the merge by mistake and none of it actually works yet. You shouldn't need npm to use this. 

`rover_launch_local` should be run from inside the misc dir. We should probably make it usable from anywhere, but that is another issue. If my memory serves me correctly `rover_on_board_node_launch` must be run from inside misc as well, but maybe that has been fixed.

**Comment by wfvining** [comment]
Corrected in latest PR #216

**Comment by Carter90** [comment]
Great, Cabrillo will take it for a spin tomorrow.

**Comment by cabrillorobotics** [comment]
No luck on our part today getting it to run properly. Documentation was not clear.
