### ISSUE TITLE
[Question] rover_onboard_node_launch.sh vs Deploy.sh

### ISSUE THREAD

**Issue by jalil29** [BCLab-UNM/SwarmBaseCode-ROS#214]
I do realize that this might not be the appropriate location to post this, but I do not know where to do so.
I am a new member to my Swarmathon Team. During our first local trial we used the  rover_onboard_node_launch.sh script to deploy the units, but a week or two later on when I was trying to run to units myself so I can troubleshoot code I had done I had discovered the deploy.sh script. 

The issue is that when we ran a certain code that had an else-if statement in the SearchController.cpp it caused an error where the unit would just spin in place with the rover_onboard script. When I ran the same controller with Deploy.sh script it did not spin in place like it did in the past. 
Talking with a former member of our team else-if was apparently a known issue in our team for use in the search controller. 

Well unfortunately I am unable to take the robots outside for testing  due to rain to validate the certainty of a successful deployment nor was I able to validate the rover_onboard issue myself since i did not know how to deploy by said method.

Talking to our professor he cited that NASA or such entity had mentioned using rover_onboard instead of Deploy.sh and can not remember or find a reason for said change. Was wondering if anyone would be kind enough to clarify the reason.

**Comment by wfvining** [comment]
Hi @jalil29 . Could you please ask this question on the Q&A [forums](http://nasaswarmathon.com/2018-qa-forum/)?
