### ISSUE TITLE
gui and status topics

### ISSUE THREAD

**Issue by m241dan** [BCLab-UNM/SwarmBaseCode-ROS#220]
The GUI generally subscribes to anything that ends in /status as a rover.

This is typically something that can be avoided by making your own new topics be like... "/status_update".

The problem arises when you want to use something like the ROS Actionlib and it comes with a built-in /status ending topic of its own (the developer can't change that if it wants to use the actionlib).

Is there any way we can change the gui's subscriber habits to like "/gui_rover_status" instead of just plain "/status"? (Can make the change myself and submit pull request if that's something would make the process easier)

**Comment by gmfricke** [comment]
We would be OK with that if the status is swarmie_status rather than gui_rover_status. We look forward to your pull request!

Matthew
