### ISSUE TITLE
Node name collisions in swarmie.launch

### ISSUE THREAD

**Issue by darrenchurchill** [BCLab-UNM/SwarmBaseCode-ROS#233]
Hey guys,

I saw that you merged a lot of pull requests this afternoon, and it looks like 3dc05c7429e5a3ca9eca2d5a08c0de286f74d139 introduced an error. The topic_tools throttle nodes all launch in the global ROS namespace with the same name, so every time a new rover comes up in the simulation, the previous rover's throttle nodes receive shutdown requests due to name collisions.

This causes the GUI to only be able to subscribe to sensor data from the rover brought up most recently. Prefixing node names with 'rovername_' like is done with the rest of the nodes should fix the problem.

**Comment by wfvining** [comment]
Thanks for catching this @darrenchurchill. Should be a simple fix. Feel free to submit a PR if you have time, otherwise I will get to it Monday or Tuesday.

**Comment by gmfricke** [comment]
Thanks for catching this! Resolved by #235.
