### ISSUE TITLE
Modify drop off routine

### ISSUE THREAD

**Issue by JCHJones** [BCLab-UNM/SwarmBaseCode-ROS#34]
by using the new collection disk issue #33 we can now guarantee that a drop off event will place a cube inside the center and no longer will robots get stuck in the center

This is possible due to the tags around the edge all pointing towards the center.

Potential feature addition given time to complete it.

**Comment by gmfricke** [comment]
Getting stuck in the center is addressed in 586cf7a7822d1e514ed9ea046a73f2a78dc3d0d8
