### ISSUE TITLE
[bug] GUI crashes when disconnected physical rover is clicked on

### ISSUE THREAD

**Issue by Antonio-Griego** [BCLab-UNM/SwarmBaseCode-ROS#55]
GUI crashes when disconnected physical rover is clicked on

That is, if a physical rover was being run and it is turned off or disconnected and you start a new simulation with simulated rovers, clicking on the now disconnected physical rover will cause the GUI to crash.

The problem:
    physical rovers need to be removed from the rover list when they are disconnected or turned off.

**Comment by gmfricke** [comment]
Fixed in [release v1.3.21-beta](https://github.com/BCLab-UNM/SwarmBaseCode-ROS/releases/tag/v1.3.21-beta).
