### ISSUE TITLE
Rover oscillates or stops moving without apparent cause

### ISSUE THREAD

**Issue by JCHJones** [BCLab-UNM/SwarmBaseCode-ROS#56]
Non-deterministic bug appears reliably in sim with 3 robots however it is not always the same robot or at the same point in time.

Needs to be tested in physical before a fix is pursued.

**Comment by kristiana-rendon** [comment]
I let the rovers run for close to an hour (picking up cubes, dropping them off, and randomly searching). I was not able to recreate this bug.

**Comment by gmfricke** [comment]
This appears to be sim only. @jschlind411

**Comment by wfvining** [comment]
No longer reliably reproducible, seems that even if the robots get into this state they eventually break out and start moving.
