### ISSUE TITLE
GUI crashes when rover is loaded into the interface without being fully initialized

### ISSUE THREAD

**Issue by jschlind411** [BCLab-UNM/SwarmBaseCode-ROS#79]
Once running the GUI and after connecting a physical rover to the GUI:

Clicking on the rover inside the GUI while any text is red will crash the GUI suddenly.

If you wait until the rover has fully connected (everything is green) it will act normally.

May be a null value issue.

**Comment by gmfricke** [comment]
This has been fixed.
