### ISSUE TITLE
Rover can get in to a "locked-up" state

### ISSUE THREAD

**Issue by wfvining** [BCLab-UNM/SwarmBaseCode-ROS#91]
Rover can get in to a state when rotating to face the waypoint where it appears to be fighting itself, and does not move. It sits in one place and makes high pitched motor noises. In some cases it thinks that is is moving, other cases it will get out of the state and drive to the waypoint.

**Comment by wfvining** [comment]
Jarrett says that the noise may be the motors getting insufficient power the robot.

**Comment by gmfricke** [comment]
Fixed in #119.
