### ISSUE TITLE
Waypoint bug. Rovers do not always recognize that the waypoint has been reached.

### ISSUE THREAD

**Issue by gmfricke** [BCLab-UNM/SwarmBaseCode-ROS#92]

**Comment by wfvining** [comment]
This is apparent when a waypoint registers as "cleared" on the map, but the rover keeps moving. Part or all of this is related to issue #58, the fix for which which does appear to fix this problem. As noted in that issue needs further testing.

**Comment by gmfricke** [comment]
Fixed in #114
