### ISSUE TITLE
Dead Link on README

### ISSUE THREAD

**Issue by kristiana-rendon** [BCLab-UNM/SwarmBaseCode-ROS#94]
The Quick Start Guide link on the README yields a 404 error. I believe it should be https://github.com/BCLab-UNM/Swarmathon-Docs/blob/master/PhysicalInstallGuide.md

**Comment by Antonio-Griego** [comment]
I believe that this issue should be closed because it appears to have been fixed by this commit:
aafeaa0ef6f5cb0f7ecbebcdc85403fe8d978335

If I am mistaken, please feel free to re-open this issue as needed. @gmfricke  @kristiana-rendon

**Comment by gmfricke** [comment]
Fixed in pull request #98
